export const pronouns = ["I", "he", "she", "we", "they", "you", "it"];

export const verbs = {
  beginner: [
    { base: "have", pastTense: "had" },
    { base: "do", pastTense: "did" },
    { base: "say", pastTense: "said" },
    { base: "get", pastTense: "got" },
    { base: "make", pastTense: "made" },
    { base: "go", pastTense: "went" },
    { base: "see", pastTense: "saw" },
    { base: "know", pastTense: "knew" },
    { base: "take", pastTense: "took" },
    { base: "think", pastTense: "thought" },
    { base: "come", pastTense: "came" },
    { base: "give", pastTense: "gave" },
    { base: "look", pastTense: "looked" },
    { base: "use", pastTense: "used" },
    { base: "find", pastTense: "found" },
    { base: "put", pastTense: "put" },
    { base: "leave", pastTense: "left" },
    { base: "work", pastTense: "worked" },
    { base: "feel", pastTense: "felt" },
    { base: "ask", pastTense: "asked" },
    { base: "show", pastTense: "showed" },
    { base: "try", pastTense: "tried" },
    { base: "call", pastTense: "called" },
    { base: "hold", pastTense: "held" },
    { base: "turn", pastTense: "turned" },
    { base: "begin", pastTense: "began" },
    { base: "like", pastTense: "liked" },
    { base: "help", pastTense: "helped" },
    { base: "start", pastTense: "started" },
    { base: "run", pastTense: "ran" },
    { base: "write", pastTense: "wrote" },
    { base: "move", pastTense: "moved" },
    { base: "play", pastTense: "played" },
    { base: "pay", pastTense: "paid" },
    { base: "hear", pastTense: "heard" },
    { base: "meet", pastTense: "met" },
    { base: "live", pastTense: "lived" },
    { base: "stand", pastTense: "stood" },
    { base: "carry", pastTense: "carried" },
    { base: "talk", pastTense: "talked" },
    { base: "sit", pastTense: "sat" },
    { base: "read", pastTense: "read" },
    { base: "continue", pastTense: "continued" },
    { base: "lose", pastTense: "lost" },
    { base: "fall", pastTense: "fell" },
    { base: "remember", pastTense: "remembered" },
    { base: "buy", pastTense: "bought" },
    { base: "speak", pastTense: "spoke" },
    { base: "stop", pastTense: "stopped" },
    { base: "win", pastTense: "won" },
    { base: "understand", pastTense: "understood" },
    { base: "open", pastTense: "opened" },
    { base: "return", pastTense: "returned" },
    { base: "draw", pastTense: "drew" },
    { base: "walk", pastTense: "walked" },
    { base: "sell", pastTense: "sold" },
    { base: "wait", pastTense: "waited" },
    { base: "watch", pastTense: "watched" },
    { base: "break", pastTense: "broke" },
    { base: "learn", pastTense: "learned" },
    { base: "explain", pastTense: "explained" },
    { base: "grow", pastTense: "grew" },
    { base: "cut", pastTense: "cut" },
    { base: "drive", pastTense: "drove" },
    { base: "catch", pastTense: "caught" },
    { base: "enjoy", pastTense: "enjoyed" },
    { base: "introduce", pastTense: "introduced" },
    { base: "eat", pastTense: "ate" },
    { base: "arrive", pastTense: "arrived" },
    { base: "close", pastTense: "closed" },
    { base: "thank", pastTense: "thanked" },
    { base: "finish", pastTense: "finished" },
    { base: "listen", pastTense: "listened" },
    { base: "smile", pastTense: "smiled" },
    { base: "teach", pastTense: "taught" },
    { base: "answer", pastTense: "answered" },
    { base: "study", pastTense: "studied" },
    { base: "fly", pastTense: "flew" },
    { base: "drink", pastTense: "drank" },
    { base: "sing", pastTense: "sang" },
    { base: "ride", pastTense: "rode" },
    { base: "jump", pastTense: "jumped" },
    { base: "wash", pastTense: "washed" },
    { base: "paint", pastTense: "painted" },
    { base: "clean", pastTense: "cleaned" },
    { base: "cook", pastTense: "cooked" },
    { base: "swim", pastTense: "swam" }
  ],
  common1000: [
    { base: "be", pastTense: "" },
    { base: "have", pastTense: "had" },
    { base: "do", pastTense: "did" },
    { base: "will", pastTense: "" },
    { base: "say", pastTense: "said" },
    { base: "would", pastTense: "" },
    { base: "can", pastTense: "could" },
    { base: "get", pastTense: "got" },
    { base: "make", pastTense: "made" },
    { base: "go", pastTense: "went" },
    { base: "see", pastTense: "saw" },
    { base: "know", pastTense: "knew" },
    { base: "take", pastTense: "took" },
    { base: "could", pastTense: "" },
    { base: "think", pastTense: "thought" },
    { base: "come", pastTense: "came" },
    { base: "give", pastTense: "gave" },
    { base: "look", pastTense: "looked" },
    { base: "may", pastTense: "" },
    { base: "should", pastTense: "" },
    { base: "use", pastTense: "used" },
    { base: "find", pastTense: "found" },
    { base: "want", pastTense: "wanted" },
    { base: "tell", pastTense: "told" },
    { base: "must", pastTense: "" },
    { base: "put", pastTense: "put" },
    { base: "mean", pastTense: "meant" },
    { base: "become", pastTense: "became" },
    { base: "leave", pastTense: "left" },
    { base: "work", pastTense: "worked" },
    { base: "need", pastTense: "needed" },
    { base: "feel", pastTense: "felt" },
    { base: "seem", pastTense: "seemed" },
    { base: "might", pastTense: "" },
    { base: "ask", pastTense: "asked" },
    { base: "show", pastTense: "showed" },
    { base: "try", pastTense: "tried" },
    { base: "call", pastTense: "called" },
    { base: "provide", pastTense: "provided" },
    { base: "keep", pastTense: "kept" },
    { base: "hold", pastTense: "held" },
    { base: "turn", pastTense: "turned" },
    { base: "follow", pastTense: "followed" },
    { base: "begin", pastTense: "began" },
    { base: "bring", pastTense: "brought" },
    { base: "like", pastTense: "liked" },
    { base: "going", pastTense: "" },
    { base: "help", pastTense: "helped" },
    { base: "start", pastTense: "started" },
    { base: "run", pastTense: "ran" },
    { base: "write", pastTense: "wrote" },
    { base: "set", pastTense: "set" },
    { base: "move", pastTense: "moved" },
    { base: "play", pastTense: "played" },
    { base: "pay", pastTense: "paid" },
    { base: "hear", pastTense: "heard" },
    { base: "include", pastTense: "included" },
    { base: "believe", pastTense: "believed" },
    { base: "allow", pastTense: "allowed" },
    { base: "meet", pastTense: "met" },
    { base: "lead", pastTense: "led" },
    { base: "live", pastTense: "lived" },
    { base: "stand", pastTense: "stood" },
    { base: "happen", pastTense: "happened" },
    { base: "carry", pastTense: "carried" },
    { base: "talk", pastTense: "talked" },
    { base: "appear", pastTense: "appeared" },
    { base: "produce", pastTense: "produced" },
    { base: "sit", pastTense: "sat" },
    { base: "offer", pastTense: "offered" },
    { base: "consider", pastTense: "condsidered" },
    { base: "suggest", pastTense: "suggested" },
    { base: "expect", pastTense: "expected" },
    { base: "read", pastTense: "read" },
    { base: "let", pastTense: "let" },
    { base: "require", pastTense: "required" },
    { base: "continue", pastTense: "continued" },
    { base: "lose", pastTense: "lost" },
    { base: "add", pastTense: "added" },
    { base: "fall", pastTense: "fell" },
    { base: "change", pastTense: "changed" },
    { base: "remember", pastTense: "remembered" },
    { base: "remain", pastTense: "remained" },
    { base: "buy", pastTense: "bought" },
    { base: "speak", pastTense: "spoke" },
    { base: "stop", pastTense: "stopped" },
    { base: "send", pastTense: "sent" },
    { base: "receive", pastTense: "received" },
    { base: "decide", pastTense: "decided" },
    { base: "win", pastTense: "won" },
    { base: "understand", pastTense: "understood" },
    { base: "develop", pastTense: "developed" },
    { base: "describe", pastTense: "described" },
    { base: "agree", pastTense: "agreed" },
    { base: "open", pastTense: "opened" },
    { base: "reach", pastTense: "reached" },
    { base: "build", pastTense: "built" },
    { base: "involve", pastTense: "involved" },
    { base: "spend", pastTense: "spent" },
    { base: "return", pastTense: "returned" },
    { base: "draw", pastTense: "drew" },
    { base: "die", pastTense: "died" },
    { base: "hope", pastTense: "hoped" },
    { base: "create", pastTense: "created" },
    { base: "walk", pastTense: "walked" },
    { base: "sell", pastTense: "sold" },
    { base: "wait", pastTense: "waited" },
    { base: "shall", pastTense: "" },
    { base: "cause", pastTense: "caused" },
    { base: "pass", pastTense: "passed" },
    { base: "lie", pastTense: "lied" },
    { base: "accept", pastTense: "accepted" },
    { base: "watch", pastTense: "watched" },
    { base: "raise", pastTense: "raised" },
    { base: "base", pastTense: "based" },
    { base: "apply", pastTense: "applied" },
    { base: "break", pastTense: "broke" },
    { base: "learn", pastTense: "learned" },
    { base: "explain", pastTense: "explained" },
    { base: "increase", pastTense: "increased" },
    { base: "cover", pastTense: "covered" },
    { base: "grow", pastTense: "grew" },
    { base: "report", pastTense: "reported" },
    { base: "claim", pastTense: "claimed" },
    { base: "support", pastTense: "supported" },
    { base: "cut", pastTense: "cut" },
    { base: "form", pastTense: "formed" },
    { base: "stay", pastTense: "stayed" },
    { base: "contain", pastTense: "contained" },
    { base: "reduce", pastTense: "reduced" },
    { base: "establish", pastTense: "established" },
    { base: "join", pastTense: "joined" },
    { base: "wish", pastTense: "wished" },
    { base: "seek", pastTense: "seeked" },
    { base: "achieve", pastTense: "achieve" },
    { base: "choose", pastTense: "chose" },
    { base: "deal", pastTense: "dealt" },
    { base: "face", pastTense: "faced" },
    { base: "fail", pastTense: "failed" },
    { base: "serve", pastTense: "served" },
    { base: "end", pastTense: "ended" },
    { base: "occur", pastTense: "occured" },
    { base: "kill", pastTense: "killed" },
    { base: "used", pastTense: "" },
    { base: "drive", pastTense: "drove" },
    { base: "represent", pastTense: "represented" },
    { base: "rise", pastTense: "rose" },
    { base: "discuss", pastTense: "discussed" },
    { base: "place", pastTense: "placed" },
    { base: "love", pastTense: "loved" },
    { base: "pick", pastTense: "picked" },
    { base: "prove", pastTense: "proved" },
    { base: "wear", pastTense: "wore" },
    { base: "argue", pastTense: "argued" },
    { base: "catch", pastTense: "caught" },
    { base: "enjoy", pastTense: "enjoyed" },
    { base: "introduce", pastTense: "introduced" },
    { base: "eat", pastTense: "ate" },
    { base: "enter", pastTense: "entered" },
    { base: "present", pastTense: "presented" },
    { base: "point", pastTense: "pointed" },
    { base: "arrive", pastTense: "arrived" },
    { base: "ensure", pastTense: "ensured" },
    { base: "plan", pastTense: "planned" },
    { base: "pull", pastTense: "pulled" },
    { base: "refer", pastTense: "referred" },
    { base: "act", pastTense: "acted" },
    { base: "relate", pastTense: "related" },
    { base: "affect", pastTense: "affected" },
    { base: "close", pastTense: "closed" },
    { base: "manage", pastTense: "managed" },
    { base: "identify", pastTense: "identified" },
    { base: "thank", pastTense: "thanked" },
    { base: "compare", pastTense: "compared" },
    { base: "obtain", pastTense: "obtained" },
    { base: "announce", pastTense: "announced" },
    { base: "note", pastTense: "noted" },
    { base: "forget", pastTense: "forgot" },
    { base: "indicate", pastTense: "indicated" },
    { base: "wonder", pastTense: "wondered" },
    { base: "maintain", pastTense: "maintained" },
    { base: "suffer", pastTense: "suffered" },
    { base: "publish", pastTense: "published" },
    { base: "express", pastTense: "expressed" },
    { base: "avoid", pastTense: "avoided" },
    { base: "suppose", pastTense: "supposed" },
    { base: "finish", pastTense: "finished" },
    { base: "determine", pastTense: "determined" },
    { base: "tend", pastTense: "tended" },
    { base: "save", pastTense: "saved" },
    { base: "listen", pastTense: "listened" },
    { base: "design", pastTense: "designed" },
    { base: "treat", pastTense: "treated" },
    { base: "share", pastTense: "shared" },
    { base: "control", pastTense: "controlled" },
    { base: "remove", pastTense: "removed" },
    { base: "visit", pastTense: "visited" },
    { base: "throw", pastTense: "threw" },
    { base: "exist", pastTense: "existed" },
    { base: "encourage", pastTense: "encouraged" },
    { base: "force", pastTense: "forced" },
    { base: "reflect", pastTense: "reflected" },
    { base: "smile", pastTense: "smiled" },
    { base: "admit", pastTense: "admitted" },
    { base: "assume", pastTense: "assumed" },
    { base: "replace", pastTense: "replaced" },
    { base: "prepare", pastTense: "prepared" },
    { base: "improve", pastTense: "improved" },
    { base: "fill", pastTense: "filled" },
    { base: "mention", pastTense: "mentioned" },
    { base: "fight", pastTense: "fought" },
    { base: "miss", pastTense: "missed" },
    { base: "intend", pastTense: "intended" },
    { base: "drop", pastTense: "dropped" },
    { base: "push", pastTense: "pushed" },
    { base: "hit", pastTense: "hit" },
    { base: "discover", pastTense: "discovered" },
    { base: "refuse", pastTense: "refused" },
    { base: "prevent", pastTense: "prevented" },
    { base: "regard", pastTense: "regarded" },
    { base: "teach", pastTense: "" },
    { base: "lay", pastTense: "" },
    "reveal",
    "state",
    "operate",
    "answer",
    "record",
    "depend",
    "enable",
    "complete",
    "cost",
    "sound",
    "check",
    "laugh",
    "realise",
    "extend",
    "arise",
    "notice",
    "define",
    "fit",
    "examine",
    "study",
    "recognise",
    "bear",
    "shake",
    "hang",
    "sign",
    "attend",
    "fly",
    "gain",
    "perform",
    "result",
    "travel",
    "protect",
    "adopt",
    "confirm",
    "let_'s",
    "stare",
    "demand",
    "imagine",
    "beat",
    "attempt",
    "born",
    "associate",
    "marry",
    "care",
    "voice",
    "collect",
    "employ",
    "issue",
    "release",
    "mind",
    "emerge",
    "mark",
    "deny",
    "aim",
    "shoot",
    "appoint",
    "supply",
    "order",
    "observe",
    "reply",
    "drink",
    "strike",
    "settle",
    "ring",
    "propose",
    "ignore",
    "link",
    "press",
    "respond",
    "survive",
    "arrange",
    "concentrate",
    "lift",
    "cross",
    "approach",
    "test",
    "experience",
    "touch",
    "charge",
    "sleep",
    "grant",
    "prefer",
    "commit",
    "threaten",
    "acquire",
    "repeat",
    "demonstrate",
    "feed",
    "insist",
    "launch",
    "promote",
    "limit",
    "measure",
    "deliver",
    "retain",
    "own",
    "consist",
    "attract",
    "promise",
    "assess",
    "hide",
    "reject",
    "belong",
    "contribute",
    "invite",
    "vary",
    "cry",
    "impose",
    "sing",
    "warn",
    "declare",
    "destroy",
    "worry",
    "address",
    "name",
    "head",
    "ought",
    "stick",
    "divide",
    "nod",
    "train",
    "recognize",
    "clear",
    "undertake",
    "combine",
    "spread",
    "attack",
    "recommend",
    "handle",
    "shout",
    "realize",
    "influence",
    "select",
    "account",
    "step",
    "welcome",
    "recall",
    "secure",
    "climb",
    "transfer",
    "contact",
    "conclude",
    "organise",
    "imply",
    "display",
    "disappear",
    "illustrate",
    "dress",
    "investigate",
    "direct",
    "generate",
    "escape",
    "remind",
    "rely",
    "succeed",
    "advise",
    "hand",
    "inform",
    "afford",
    "earn",
    "fear",
    "approve",
    "vote",
    "burn",
    "matter",
    "last",
    "ride",
    "jump",
    "match",
    "gather",
    "derive",
    "conduct",
    "shut",
    "elect",
    "cope",
    "persuade",
    "recover",
    "blow",
    "estimate",
    "score",
    "slip",
    "hate",
    "count",
    "lean",
    "exercise",
    "roll",
    "attach",
    "house",
    "wash",
    "explore",
    "rest",
    "accompany",
    "accuse",
    "judge",
    "bind",
    "steal",
    "stretch",
    "comment",
    "withdraw",
    "exclude",
    "focus",
    "hurt",
    "pursue",
    "fix",
    "back",
    "switch",
    "justify",
    "knock",
    "permit",
    "occupy",
    "surround",
    "lack",
    "list",
    "benefit",
    "appreciate",
    "paint",
    "connect",
    "abandon",
    "engage",
    "construct",
    "complain",
    "quote",
    "dominate",
    "view",
    "blame",
    "separate",
    "proceed",
    "dismiss",
    "incorporate",
    "stress",
    "acknowledge",
    "search",
    "interpret",
    "defend",
    "alter",
    "arrest",
    "expand",
    "suit",
    "tie",
    "analyse",
    "possess",
    "bother",
    "implement",
    "review",
    "mix",
    "calculate",
    "resolve",
    "assist",
    "suspect",
    "wake",
    "question",
    "glance",
    "rule",
    "reckon",
    "appeal",
    "specify",
    "guess",
    "damage",
    "restore",
    "challenge",
    "clean",
    "restrict",
    "distinguish",
    "urge",
    "trust",
    "constitute",
    "convert",
    "submit",
    "feature",
    "land",
    "solve",
    "sort",
    "predict",
    "struggle",
    "locate",
    "preserve",
    "owe",
    "cook",
    "pour",
    "shift",
    "cast",
    "lock",
    "dance",
    "invest",
    "kick",
    "race",
    "kiss",
    "light",
    "purchase",
    "retire",
    "monitor",
    "breathe",
    "bend",
    "register",
    "celebrate",
    "resist",
    "print",
    "date",
    "fire",
    "organize",
    "comprise",
    "swing",
    "finance",
    "detect",
    "range",
    "overcome",
    "decline",
    "behave",
    "differ",
    "need",
    "guarantee",
    "relax",
    "store",
    "oppose",
    "resign",
    "rush",
    "waste",
    "drag",
    "pause",
    "pack",
    "install",
    "compete",
    "sink",
    "expose",
    "whisper",
    "split",
    "negotiate",
    "mount",
    "found",
    "sweep",
    "distribute",
    "capture",
    "enhance",
    "doubt",
    "deserve",
    "award",
    "phone",
    "bury",
    "tackle",
    "assure",
    "borrow",
    "exceed",
    "emphasise",
    "slide",
    "transform",
    "qualify",
    "cease",
    "concern",
    "advance",
    "strengthen",
    "perceive",
    "favour",
    "practise",
    "tear",
    "scream",
    "sustain",
    "participate",
    "pose",
    "lend",
    "satisfy",
    "grab",
    "smoke",
    "consult",
    "outline",
    "dry",
    "adapt",
    "reinforce",
    "adjust",
    "shrug",
    "dig",
    "snap",
    "ban",
    "highlight",
    "encounter",
    "pretend",
    "wave",
    "request",
    "trade",
    "sail",
    "rid",
    "amount",
    "confine",
    "trace",
    "absorb",
    "block",
    "entitle",
    "delay",
    "plant",
    "react",
    "dream",
    "fulfil",
    "flow",
    "cite",
    "lower",
    "seize",
    "process",
    "swim",
    "allocate",
    "communicate",
    "govern",
    "defeat",
    "injure",
    "fund",
    "protest",
    "stir",
    "hurry",
    "smell",
    "wander",
    "burst",
    "exploit",
    "pray",
    "sigh",
    "double",
    "undergo",
    "ease",
    "wipe",
    "evaluate",
    "compose",
    "eliminate",
    "wrap",
    "grin",
    "confront",
    "remark",
    "interview",
    "collapse",
    "anticipate",
    "weigh",
    "suspend",
    "slow",
    "attribute",
    "condemn",
    "bound",
    "murder",
    "spot",
    "dare",
    "cancel",
    "gaze",
    "wind",
    "swear",
    "telephone",
    "balance",
    "free",
    "reverse",
    "inspire",
    "modify",
    "bet",
    "devise",
    "correspond",
    "prompt",
    "convince",
    "rub",
    "guide",
    "shine",
    "bite",
    "crash",
    "hesitate",
    "swallow",
    "integrate",
    "induce",
    "greet",
    "tap",
    "murmur",
    "load",
    "translate",
    "knit",
    "yield",
    "admire",
    "line",
    "render",
    "disturb",
    "shape",
    "flee",
    "interrupt",
    "chase",
    "copy",
    "leap",
    "devote",
    "overlook",
    "witness",
    "mutter",
    "risk",
    "accommodate",
    "brush",
    "assert",
    "book",
    "age",
    "await",
    "criticise",
    "spell",
    "trap",
    "comply",
    "forgive",
    "initiate",
    "undermine",
    "squeeze",
    "evolve",
    "stimulate",
    "enforce",
    "provoke",
    "drift",
    "in",
    "situate",
    "sense",
    "emphasize",
    "research",
    "freeze",
    "exchange",
    "hire",
    "pop",
    "object",
    "recruit",
    "beg",
    "float",
    "echo",
    "fade",
    "consume",
    "value",
    "equip",
    "progress",
    "reserve",
    "execute",
    "convey",
    "park",
    "unite",
    "twist",
    "respect",
    "administer",
    "command",
    "educate",
    "invent",
    "abolish",
    "correct",
    "allege",
    "frown",
    "march",
    "fetch",
    "envisage",
    "resemble",
    "price",
    "repair",
    "exhibit",
    "instruct",
    "resume",
    "plead",
    "insert",
    "export",
    "update",
    "assign",
    "cater",
    "concede",
    "opt",
    "persist",
    "isolate",
    "spin",
    "disclose",
    "spring",
    "conceive",
    "interfere",
    "regulate",
    "peer",
    "fancy",
    "inherit",
    "speed",
    "regret",
    "extract",
    "label",
    "descend",
    "boost",
    "incur",
    "facilitate",
    "fold",
    "please",
    "excuse",
    "intervene",
    "criticize",
    "conceal",
    "tip",
    "flash",
    "advocate",
    "breed",
    "grasp",
    "explode",
    "assemble",
    "upset",
    "commission",
    "embrace",
    "decorate",
    "drain",
    "edit",
    "contemplate",
    "strip",
    "function",
    "rescue",
    "cling",
    "deem",
    "centre",
    "sponsor",
    "reproduce",
    "confess",
    "contract",
    "decrease",
    "endorse",
    "coincide",
    "spare",
    "creep",
    "schedule",
    "ship",
    "dump",
    "market",
    "vanish",
    "scatter",
    "shop",
    "sue",
    "stage",
    "tempt",
    "import",
    "formulate",
    "classify",
    "aid",
    "advertise",
    "impress",
    "crack",
    "suck",
    "dispose",
    "dissolve",
    "warm",
    "omit",
    "praise",
    "subject",
    "tremble",
    "signal",
    "enclose",
    "commence",
    "taste",
    "halt",
    "tighten",
    "discharge",
    "top",
    "draft",
    "enquire",
    "erect",
    "hunt",
    "access",
    "smash",
    "depict",
    "inspect",
    "spoil",
    "target",
    "reward",
    "file",
    "relieve",
    "contrast",
    "seal",
    "round",
    "precede",
    "originate",
    "tuck",
    "clarify",
    "bid",
    "melt",
    "thrust",
    "widen",
    "summon",
    "amend",
    "desire",
    "compensate",
    "couple",
    "plunge",
    "depart",
    "circulate",
    "characterise",
    "surprise",
    "sum",
    "guard",
    "stem",
    "weaken",
    "shed",
    "manufacture",
    "drown",
    "activate",
    "diminish",
    "rain",
    "bang",
    "arouse",
    "suppress",
    "slam",
    "transmit",
    "rent",
    "neglect",
    "tour",
    "entertain",
    "fling",
    "spill",
    "figure",
    "tax",
    "cool",
    "compile",
    "transport",
    "entail",
    "reassure",
    "embark",
    "bow",
    "deprive",
    "revive",
    "sentence",
    "campaign",
    "supplement",
    "project",
    "part",
    "forbid",
    "effect",
    "calm",
    "manipulate",
    "debate",
    "chat",
    "time",
    "punish",
    "supervise",
    "substitute",
    "convict",
    "strain",
    "flood",
    "dedicate",
    "rebuild",
    "toss",
    "regain",
    "characterize",
    "disagree",
    "dictate",
    "stroke",
    "confuse",
    "underline",
    "confer",
    "position",
    "clutch",
    "bounce",
    "pin",
    "counter",
    "grip",
    "prescribe",
    "long",
    "merge",
    "proclaim",
    "conform",
    "term",
    "sack",
    "heat",
    "crush",
    "attain",
    "trigger",
    "renew",
    "cheer",
    "rip",
    "frighten",
    "shiver",
    "arm",
    "total",
    "dislike",
    "boast",
    "embody",
    "stamp",
    "weep",
    "penetrate",
    "multiply",
    "stuff",
    "exert",
    "abuse",
    "compel",
    "presume",
    "scratch",
    "boil",
    "exhaust",
    "snatch",
    "motivate",
    "inhibit",
    "prevail",
    "colour",
    "rate",
    "yell"
  ]
};
